name: Feed Event

on:
  workflow_call:
    outputs:
      changed:
        description: "1 if feed files were updated"
        value: ${{ jobs.run.outputs.changed }}
      sha:
        description: "Commit SHA that contains the generated feed"
        value: ${{ jobs.run.outputs.sha }}
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pages: write
  id-token: write

concurrency:
  group: feed
  cancel-in-progress: false

jobs:
  run:
    uses: ./.github/workflows/event_core.yml
    permissions:
      actions: read
      contents: write
      pages: write
      id-token: write
    with:
      avatar_image: "image/avatar/event.png"
    secrets: inherit
