name: Feed Spot Intro

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

concurrency:
  group: feed
  cancel-in-progress: false

jobs:
  run:
    uses: ./.github/workflows/feed_slot_guide_random.yml
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      avatar_image: "image/avatar/spot.png"
      place: "Yokosuka"
      post_to_x: "1"
    secrets: inherit
